#!/usr/bin/env python3
"""HyperTraceX PDF Report Templates - Professional forensic report templates."""

import os
from datetime import datetime
from typing import Dict, List, Optional

try:
    from core.logger import get_logger
except ImportError:
    import logging
    def get_logger(name="HyperTraceX"):
        return logging.getLogger(name)

try:
    from fpdf import FPDF
    FPDF_AVAILABLE = True
except ImportError:
    FPDF_AVAILABLE = False


class PDFTemplate:
    """Base PDF template with professional styling."""
    
    def __init__(self, logger=None):
        self.logger = logger or get_logger()
        self.pdf = None
        
        if not FPDF_AVAILABLE:
            self.logger.warning("fpdf not installed")
    
    def _setup_document(self, title: str = "Forensic Report"):
        """Setup PDF document with professional styling."""
        self.pdf = FPDF()
        self.pdf.set_auto_page_break(auto=True, margin=20)
        self.pdf.add_page()
        
        self.pdf.set_font("Helvetica", "B", 24)
        self.pdf.cell(0, 15, title, align="C", new_x="LMARGIN", new_y="NEXT")
        self.pdf.ln(5)
        
        self.pdf.set_draw_color(0, 51, 102)
        self.pdf.set_line_width(0.5)
        self.pdf.line(10, self.pdf.get_y(), 200, self.pdf.get_y())
        self.pdf.ln(10)
    
    def _add_header(self, text: str):
        self.pdf.set_font("Helvetica", "B", 14)
        self.pdf.set_text_color(0, 51, 102)
        self.pdf.cell(0, 10, text, new_x="LMARGIN", new_y="NEXT")
        self.pdf.set_draw_color(0, 51, 102)
        self.pdf.line(10, self.pdf.get_y(), 200, self.pdf.get_y())
        self.pdf.ln(5)
        self.pdf.set_text_color(0, 0, 0)
    
    def _add_paragraph(self, text: str):
        self.pdf.set_font("Helvetica", "", 10)
        self.pdf.multi_cell(0, 6, text)
        self.pdf.ln(3)
    
    def _add_table(self, headers: List[str], data: List[List], col_widths: List[int] = None):
        if not col_widths:
            col_widths = [190 // len(headers)] * len(headers)
        
        self.pdf.set_font("Helvetica", "B", 9)
        self.pdf.set_fill_color(0, 51, 102)
        self.pdf.set_text_color(255, 255, 255)
        
        for i, (header, width) in enumerate(zip(headers, col_widths)):
            self.pdf.cell(width, 8, header, border=1, fill=True, align="C")
        self.pdf.ln()
        
        self.pdf.set_text_color(0, 0, 0)
        self.pdf.set_font("Helvetica", "", 8)
        
        for row_idx, row in enumerate(data):
            fill = row_idx % 2 == 0
            if fill:
                self.pdf.set_fill_color(240, 245, 250)
            
            for i, (cell, width) in enumerate(zip(row, col_widths)):
                self.pdf.cell(width, 7, str(cell)[:width//2], border=1, fill=fill)
            self.pdf.ln()
        
        self.pdf.ln(5)
    
    def _add_footer(self):
        self.pdf.set_y(-20)
        self.pdf.set_font("Helvetica", "I", 8)
        self.pdf.set_text_color(128, 128, 128)
        self.pdf.cell(0, 10, f"Generated by HyperTraceX v1.0.0 | Page {self.pdf.page_no()}/{{nb}}", align="C")
        self.pdf.cell(0, 5, "CONFIDENTIAL - FOR AUTHORIZED PERSONNEL ONLY", align="C", new_x="LMARGIN", new_y="NEXT")


class ExecutiveReportTemplate(PDFTemplate):
    """Executive summary report template."""
    
    def generate(self, case_info: Dict, statistics: Dict, output_file: str) -> Optional[str]:
        if not FPDF_AVAILABLE:
            return None
        
        self._setup_document("Executive Summary Report")
        
        self._add_header("Case Overview")
        self._add_paragraph(f"Case ID: {case_info.get('case_id', 'N/A')}")
        self._add_paragraph(f"Investigator: {case_info.get('investigator', 'N/A')}")
        self._add_paragraph(f"Organization: {case_info.get('organization', 'N/A')}")
        self._add_paragraph(f"Date: {case_info.get('generated_at', datetime.now().isoformat())[:19]}")
        
        self._add_header("Key Findings")
        findings = statistics.get("findings", ["No findings reported"])
        for finding in findings[:5]:
            self._add_paragraph(f"• {finding}")
        
        self._add_header("Statistics Summary")
        stats_data = [
            ["Total Evidence Items", str(statistics.get("total_evidence", 0))],
            ["Total Size", f"{statistics.get('total_size_gb', 0):.2f} GB"],
            ["Files Analyzed", str(statistics.get("files_analyzed", 0))],
            ["Anomalies Detected", str(statistics.get("anomalies", 0))],
            ["Custody Entries", str(statistics.get("custody_entries", 0))],
        ]
        self._add_table(["Metric", "Value"], stats_data, [120, 70])
        
        self._add_header("Recommendations")
        recommendations = statistics.get("recommendations", ["Continue investigation"])
        for rec in recommendations[:3]:
            self._add_paragraph(f"• {rec}")
        
        self._add_footer()
        
        os.makedirs(os.path.dirname(output_file) if os.path.dirname(output_file) else ".", exist_ok=True)
        self.pdf.output(output_file)
        print(f"[+] Executive report: {output_file}")
        return output_file


class EvidenceReportTemplate(PDFTemplate):
    """Evidence inventory report template."""
    
    def generate(self, case_info: Dict, evidence_list: List[Dict], output_file: str) -> Optional[str]:
        if not FPDF_AVAILABLE:
            return None
        
        self._setup_document("Evidence Inventory Report")
        
        self._add_header("Case Information")
        self._add_paragraph(f"Case ID: {case_info.get('case_id', 'N/A')}")
        self._add_paragraph(f"Total Items: {len(evidence_list)}")
        
        self._add_header("Evidence Items")
        
        headers = ["File Name", "Size", "SHA256", "Acquired"]
        col_widths = [60, 30, 60, 40]
        
        data = []
        for ev in evidence_list[:50]:
            name = os.path.basename(str(ev.get("file_path", ev.get("file", "N/A"))))[:30]
            size = str(ev.get("size", ev.get("file_size", "N/A")))
            sha = str(ev.get("sha256", ev.get("sha256_hash", "N/A")))[:32]
            acquired = str(ev.get("acquired_at", ev.get("timestamp", "N/A")))[:19]
            data.append([name, size, sha, acquired])
        
        if data:
            self._add_table(headers, data, col_widths)
        else:
            self._add_paragraph("No evidence items recorded.")
        
        self._add_footer()
        
        os.makedirs(os.path.dirname(output_file) if os.path.dirname(output_file) else ".", exist_ok=True)
        self.pdf.output(output_file)
        print(f"[+] Evidence report: {output_file}")
        return output_file


class ChainOfCustodyTemplate(PDFTemplate):
    """Chain of custody report template."""
    
    def generate(self, case_info: Dict, custody_entries: List[Dict], output_file: str) -> Optional[str]:
        if not FPDF_AVAILABLE:
            return None
        
        self._setup_document("Chain of Custody Report")
        
        self._add_header("Case Information")
        self._add_paragraph(f"Case ID: {case_info.get('case_id', 'N/A')}")
        self._add_paragraph(f"Total Transfers: {len(custody_entries)}")
        
        self._add_header("Custody Log")
        
        headers = ["Date/Time", "Action", "Handler", "Location"]
        col_widths = [45, 45, 50, 50]
        
        data = []
        for entry in custody_entries[:30]:
            timestamp = str(entry.get("timestamp", "N/A"))[:19]
            action = entry.get("action", "N/A")
            handler = entry.get("handler", "N/A")
            location = entry.get("location", "N/A")
            data.append([timestamp, action, handler, location])
        
        if data:
            self._add_table(headers, data, col_widths)
        else:
            self._add_paragraph("No custody entries recorded.")
        
        self._add_header("Certification")
        self._add_paragraph(
            "I certify that the above chain of custody is complete and accurate. "
            "All evidence was handled according to established forensic procedures."
        )
        self._add_paragraph(f"Signature: ___________________________ Date: {datetime.now().strftime('%Y-%m-%d')}")
        
        self._add_footer()
        
        os.makedirs(os.path.dirname(output_file) if os.path.dirname(output_file) else ".", exist_ok=True)
        self.pdf.output(output_file)
        print(f"[+] Custody report: {output_file}")
        return output_file


class FullInvestigationTemplate(PDFTemplate):
    """Complete investigation report template."""
    
    def generate(self, case_info: Dict, evidence_list: List[Dict], 
                 analysis_results: Dict, custody_entries: List[Dict],
                 statistics: Dict, output_file: str) -> Optional[str]:
        if not FPDF_AVAILABLE:
            return None
        
        self._setup_document("Full Investigation Report")
        
        self._add_header("1. Case Overview")
        self._add_paragraph(f"Case ID: {case_info.get('case_id', 'N/A')}")
        self._add_paragraph(f"Investigator: {case_info.get('investigator', 'N/A')}")
        self._add_paragraph(f"Organization: {case_info.get('organization', 'N/A')}")
        self._add_paragraph(f"Description: {case_info.get('description', 'N/A')}")
        
        self._add_header("2. Evidence Summary")
        self._add_paragraph(f"Total evidence items collected: {len(evidence_list)}")
        
        if evidence_list:
            headers = ["File Name", "Size", "Hash"]
            col_widths = [70, 40, 80]
            data = []
            for ev in evidence_list[:20]:
                name = os.path.basename(str(ev.get("file_path", ev.get("file", "N/A"))))[:35]
                size = str(ev.get("size", ev.get("file_size", "N/A")))
                sha = str(ev.get("sha256", ev.get("sha256_hash", "N/A")))[:40]
                data.append([name, size, sha])
            self._add_table(headers, data, col_widths)
        
        self._add_header("3. Analysis Results")
        if analysis_results:
            for key, value in analysis_results.items():
                if isinstance(value, list):
                    self._add_paragraph(f"{key}: {len(value)} items found")
                elif isinstance(value, dict):
                    self._add_paragraph(f"{key}: {len(value)} categories")
                else:
                    self._add_paragraph(f"{key}: {value}")
        else:
            self._add_paragraph("No analysis results available.")
        
        self._add_header("4. Chain of Custody")
        self._add_paragraph(f"Total custody transfers: {len(custody_entries)}")
        
        if custody_entries:
            headers = ["Date/Time", "Action", "Handler"]
            col_widths = [65, 65, 60]
            data = []
            for entry in custody_entries[:15]:
                timestamp = str(entry.get("timestamp", "N/A"))[:19]
                action = entry.get("action", "N/A")
                handler = entry.get("handler", "N/A")
                data.append([timestamp, action, handler])
            self._add_table(headers, data, col_widths)
        
        self._add_header("5. Statistics")
        stats_data = []
        for key, value in statistics.items():
            if not isinstance(value, (list, dict)):
                stats_data.append([key, str(value)])
        
        if stats_data:
            self._add_table(["Metric", "Value"], stats_data, [120, 70])
        
        self._add_header("6. Investigator Certification")
        self._add_paragraph(
            "I hereby certify that the information contained in this report is accurate "
            "and complete to the best of my knowledge. All forensic procedures were followed "
            "according to industry standards and best practices."
        )
        self._add_paragraph(f"Signature: ___________________________")
        self._add_paragraph(f"Date: {datetime.now().strftime('%Y-%m-%d')}")
        self._add_paragraph(f"Investigator: {case_info.get('investigator', '________________')}")
        
        self._add_footer()
        
        os.makedirs(os.path.dirname(output_file) if os.path.dirname(output_file) else ".", exist_ok=True)
        self.pdf.output(output_file)
        print(f"[+] Full investigation report: {output_file}")
        return output_file


def generate_all_reports(case_info: Dict, evidence: List, analysis: Dict,
                         custody: List, stats: Dict, output_dir: str) -> Dict[str, str]:
    """Generate all report types."""
    reports = {}
    
    executive = ExecutiveReportTemplate()
    reports["executive"] = executive.generate(case_info, stats, 
                                               os.path.join(output_dir, "executive_report.pdf"))
    
    evidence_tpl = EvidenceReportTemplate()
    reports["evidence"] = evidence_tpl.generate(case_info, evidence,
                                                 os.path.join(output_dir, "evidence_report.pdf"))
    
    custody_tpl = ChainOfCustodyTemplate()
    reports["custody"] = custody_tpl.generate(case_info, custody,
                                               os.path.join(output_dir, "custody_report.pdf"))
    
    full_tpl = FullInvestigationTemplate()
    reports["full"] = full_tpl.generate(case_info, evidence, analysis, custody, stats,
                                         os.path.join(output_dir, "full_investigation_report.pdf"))
    
    return reports
